version: '3.8'

services:
  api:
    container_name: sru-search-api
    build:
      context: .
      dockerfile: ./api/Dockerfile
      target: production
    restart: unless-stopped
    env_file:
      - ./api/.env
    ports:
      - $PORT:$PORT_DEV
    volumes:
      - ./api/:/usr/src/app

  mongo-express:
    image: mongo-express
    container_name: mongo-admin
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: changeme
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: 'mongodb://root:password123@mongodb:27017'
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password123

networks:
  api:
    driver: search
  redis:
    driver: search
  redis-commander:
    driver: search
