version: '3.8'

networks:
  geo_default:
    external:
      name: geo_default

services:
  api:
    container_name: sru-search-api
    build:
      context: ./api
      dockerfile: Dockerfile
      target: production
    restart: unless-stopped
    env_file:
      - ./api/.env
    ports:
      - $PORT:$PORT_DEV
    volumes:
      - ./api/:/usr/src/app
    networks:
      - geo_default
